-- =============================================================================
-- 목적
--   1단계 배포에서 "선택 가능한 구"를 서울 25개 자치구로 맞추는 방법을 정리한다.
--
-- 앱 동작 (권장)
--   gourmet `.env` 에 DEPLOY_STAGE1=true 를 두면 API 가 허용 구만 노출한다.
--   broke 는 기본 빌드(VITE_BROG_FULL_MAP 미설정)에서 UI 도 동일 25구를 쓴다.
--   코드 상 기본: `deploy_stage1.py` `DEFAULT_STAGE1_DISTRICTS` = broke `data/regions.ts` `seoulDistricts`.
--
-- DB 보조 (선택)
--   API 필터만으로도 충분하다. 부팅 시 `ensure_seoul_25_district_rows()` 가 빠진 구 행을 추가한다.
--   관리 도구에서 "비활성 구"가 보이면 혼동을 줄이기 위해 아래처럼 나머지 구의 active 를 false 로 둘 수 있다.
-- =============================================================================

-- 예시: 허용 25구 외 비활성(이름 목록은 코드 DEFAULT_STAGE1_DISTRICTS 와 일치해야 함). 주석 해제 후 실행.
-- UPDATE districts SET active = false
-- WHERE name NOT IN (
--   '강남구','강동구','강북구','강서구','관악구','광진구','구로구','금천구','노원구','도봉구',
--   '동대문구','동작구','마포구','서대문구','서초구','성동구','성북구','송파구','양천구',
--   '영등포구','용산구','은평구','종로구','중구','중랑구'
-- );

-- 전국 등 무제한 전환 시 DEPLOY_STAGE1 를 끄고, 필요하면 active 를 다시 켠다.
-- UPDATE districts SET active = true;
